# Generated by Django 3.2.15 on 2022-09-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='', max_length=30)),
                ('password', models.CharField(default='', max_length=30)),
                ('fullname', models.CharField(default='', max_length=60)),
                ('emailaddr', models.CharField(default='', max_length=120)),
                ('phonenum', models.IntegerField(default='')),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
