# Generated by Django 3.2.15 on 2022-09-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxvia_be_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
