# Generated by Django 3.2.15 on 2022-09-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxvia_be_auth_app', '0002_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
