# Generated by Django 3.2.15 on 2022-09-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxvia_be_auth_app', '0003_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phonenum',
            field=models.CharField(default='', max_length=25),
        ),
    ]
