# Generated by Django 3.2.15 on 2022-09-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxvia_be_auth_app', '0004_alter_user_phonenum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='emailaddr',
            field=models.EmailField(default='', max_length=240),
        ),
    ]
