# Generated by Django 3.2.15 on 2022-09-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxvia_be_auth_app', '0005_auto_20220923_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phonenum',
        ),
    ]
