# Generated by Django 3.2.15 on 2022-09-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxvia_be_auth_app', '0006_remove_user_phonenum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='username',
        ),
    ]
