# Generated by Django 3.2.15 on 2022-09-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xxvia_be_auth_app', '0007_rename_userid_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emailaddr',
            new_name='emailaddress',
        ),
    ]
