# Generated by Django 3.2.15 on 2022-09-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxvia_be_auth_app', '0008_rename_emailaddr_user_emailaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userrole',
            field=models.CharField(default='', max_length=20),
        ),
    ]
