# Generated by Django 3.2.15 on 2022-09-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxvia_be_auth_app', '0009_user_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userrole',
            field=models.CharField(default='Customer', max_length=20),
        ),
    ]
