# Generated by Django 3.2.15 on 2022-09-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xxvia_be_auth_app', '0010_alter_user_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=300),
        ),
    ]
